#
# BASE CONFIGURATION
#

# `base_url` should only be changed if your site isn't hosted at the root of a domain.
# `domain` is used to generate absolute URLs. (required to generate a valid feed)
#
#   Example:
#       http://my-site.com/
#           base_url: /
#           domain: my-site.com
#       http://my-site.com/my-blog/
#           base_url: /my-blog/
#           domain: my-site.com
base_url: /blog/
domain: dector.github.io


#
# METADATA
#

# Used in header meta tags and the site feed. (required to generate a valid feed)
author: dector
# A description of your site to be used in header meta tags.
description: android gamedev haxe flixel development games
# Used in the site feed.
email: dector9@gmail.com
# Your site's subtitle.
subtitle: 
# Your site's title. (required to generate a valid feed)
title: Existential coder


#
# THIRD PARTY SETTINGS
#

# If you'd like to enable Google Analytics for your site, set this to your tracking code.
analytics: UA-33386330-4


#
# Chances are you probably don't need to touch anything below here.
#

archive_layout: archive.html
archives_url: /archives/
tag_layout: tag.html
tags_url: /archives/
